sudo: false
language: rust

before_script:
- pip install 'travis-cargo<0.2' --user
- export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo test
after_success:
- travis-cargo --only stable doc-upload --branch master
